### PR TITLE
Update package dependencies, metadata, and scripts

### PR DESCRIPTION
**Pull request by cmoesel**
- update dependencies (including typescript -> 3.7.x)
- fix license and repository entries
- change "ci" script to "check" (since npm has a "ci" command already)

This updates to TypeScript 3.7.x as well, which has some nice features that I think we should take advantage of.  Most notably, please be aware of _optional chaining_ and _nullish coalescing_.  See: https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html

@ngfreiter, @kjmahalingam, @mint-thompson -- I would also like to change `author` to `contributors` and add all of your names and MITRE email addresses.  Please indicate if you are comfortable with that.  @jafeltra can add her name with her first pull request. ;-)

### CODE REVIEW

**Comment by mint-thompson** [comment]
@cmoesel i am comfortable with having my name and MITRE email added to the contributors list.

**Comment by kjmahalingam** [comment]
@cmoesel I am comfortable with being added onto the list, in name and email.

**Comment by ngfreiter** [comment]
@cmoesel I am also comfortable with having my name and email added to the list.

**Comment by cmoesel** [comment]
OK, I've added you all as contributors (in alphabetical order by last name)!  When it passes Travis, can you merge it, @kjmahalingam?

**Pull request merged**
